
# Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset:1.25@sha256:90a36bc2013b3fcb28e2a4b082c9b895d7c2c679e58b95aed9721970f3339d0e as builder
ARG TARGETOS=linux
ARG TARGETARCH
ARG CGO_ENABLED=1


WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY distributions.json distributions.json

# Build the manager binary
USER root

# GOARCH is intentionally left empty to automatically detect the host architecture
# This ensures the binary matches the platform where docker-build is executed
RUN CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:57c8151c51445a07e503dab9dc9211dc3cdeac9d45ed81a10954b7d770659b3b
WORKDIR /
COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/controllers/manifests ./manifests/
USER 1001

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-ogx-operator-container" \
      description="kubernetes operator that is responsible for creating and managing ogx server" \
      summary="kubernetes operator that is responsible for creating and managing ogx server" \
      name="rhoai/odh-ogx-operator-rhel9" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-ogx-operator" \
      io.k8s.description="odh-ogx-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
