
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        serverName: ogx-k8s-operator-controller-manager-metrics-service.ogx-k8s-operator-system.svc
        ca:
          configMap:
            name: openshift-service-ca.crt
            key: service-ca.crt
  selector:
    matchLabels:
      control-plane: controller-manager
