apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ogx-k8s-operator-tls-profile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ogx-k8s-operator-tls-profile
subjects:
- kind: ServiceAccount
  name: ogx-k8s-operator-controller-manager
  namespace: ogx-k8s-operator-system
