releases:
  - name: OGX
    version: v1.3.0
    repoUrl: https://github.com/opendatahub-io/ogx-distribution
  - name: OGX Operator
    version: v0.14.0
    repoUrl: https://github.com/opendatahub-io/ogx-k8s-operator
